language: node_js

node_js:
  - 10
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: false

jobs:
  include:
  - stage: Run Tests and Produce Coverage
    script: npm test -- --collect-coverage && npm run report-coverage
  - stage: Package Build
    script: npm run build